**Scenario - 1 :**

As a part of their **end of season** sales, **GlobalMart** wishes to offer **flat 20% discount** on **sales amount** of all **item**s belonging to **Furniture** category

* **Collect** the **sales amounts** of all **Furniture** items
* Apply **20% discount** and **print** discount values

Refer to the **Sales** column of the **order details** once again :

![](https://raw.githubusercontent.com/mentorskool/python-essentials/main/Module-6-PY-Learning-4/imgs/03-order-details-03.png)

* On **eyeballing** the data you'll find the following **list of values** which belong to **Furniture** category : **2000, 700, 900, 50, 500, 200**

* How can we **store** them?
* Once stored, how can we **process** them?

* Enter **sequence data types**, specifically **Lists**

In [1]:
# Let's store only first 2 values for now
# Lists are created using square bracket
sales_amounts = [2000,700]
print(sales_amounts)

# Let's check the data type of the variable sales_amounts
print(type(sales_amounts))

[2000, 700]
<class 'list'>

In [2]:
# Let's pick the first value of the list and apply discount
sales_amount_1 = sales_amounts[0]
print('Discount applied on 1st item is :',sales_amount_1*0.2)

# How about picking the 2nd value of the list
sales_amount_2 = sales_amount_1 = sales_amounts[1]
print('Discount applied on 2nd item is :',sales_amount_2*0.2)

Discount applied on 1st item is : 400.0
Discount applied on 2nd item is : 140.0

* Did you **observe** a **pattern** above?
* We are **accessing items** of a **list** by using a **combination** of **square brackets [ ]** and a **number** starting from **0** and followed by **1,2,3 etc**.
* This idea of **using numbers** to **access items** in a list is the idea of **indexing** 

Check the **image** below to **understand** how **values of a list** are related to the **index(position)** of the values :      

![](https://raw.githubusercontent.com/mentorskool/python-essentials/main/Module-6-PY-Learning-4/imgs/06-indexing.png)

**Important Note :** 
* The **index** (or **position**) of **items** in a list **starts with 0 rather than 1** (which comes **intuitively** in mind). This may seem **wierd** but that's how programmers are. Let's go by **what's the rule**. 
* This would mean in a list of **2 items**, the **last value** will have an **index 1** rather than **2**

----------------------------------
**Scenario - 2 :**

* Your list **sales_amounts** has **2 items**. How can we add the next value, i.e **900**?
* You are asked to **change** the amount **900** to **850**. How to do that?
* You **did a mistake** and **added** the **next item as 55** instead of **50**. Remove the **last item 55** and then **add 50**
* You did another **mistake** and added **50 twice**. **Remove** **one** of the **50s**
* You **got bored** off **adding values** in the list **one by one**. You wish to add the **last two** values of **500** and **200** in **one shot**

How do we achieve the above tasks?

* **Functions** will come to our **help** here
* Lists have a number of **in-built functions** to help you do perform a **number of tasks**
* Let's work out the above scenarios below

In [3]:
# Adding next item 900
sales_amounts.append(900) 
sales_amounts

[2000, 700, 900]

In [4]:
# Change value of 900 to 850
sales_amounts[2] = 850
sales_amounts

# Note the index 2, which in the list points to 900

[2000, 700, 850]

In [5]:
# Add 55 to the list
sales_amounts.append(55) 
sales_amounts

[2000, 700, 850, 55]

In [6]:
# Remove 55 from the list
sales_amounts.remove(55)
sales_amounts

[2000, 700, 850]

In [11]:
# Add 50 2 times. Your list should have 2 values of 50
# Try removing 50 now
# What happened?
sales_amounts.append(50)
sales_amounts.append(50)
sales_amounts
# Type your code below

[2000, 700, 850, 50, 50]

In [12]:
sales_amounts.remove(50)
sales_amounts

[2000, 700, 850, 50]

In [13]:
# Let's check what the list has now
sales_amounts

[2000, 700, 850, 50]

In [14]:
# We don't know which 50 got removed, is it from index 3 or 4?
# Let's test this by first replacing 700 by 50 at index 1
sales_amounts[1] = 50
sales_amounts

[2000, 50, 850, 50]

In [15]:
# Let's try removing 50 now :
sales_amounts.remove(50)

In [16]:
# Let's check what the list has now
sales_amounts

# This should prove that on remove, the first occurence gets removed

[2000, 850, 50]

In [17]:
# Now, you wish to remove any item at index 1 whether it is 850 now or 900 later
sales_amounts.pop(1)

# Let's check what the list has now
sales_amounts

# Did you observe? The pop() method takes index as argument and not the item itself

[2000, 50]

In [18]:
# Ok, let's put 900 back at the position we had 850
sales_amounts.insert(1,900)

# Let's check what the list has now
sales_amounts

# Observe the insert function. It has 2 arguments : first one is the index at which value to be entered, the 2nd is the value itself

[2000, 900, 50]

In [19]:
# Finally how to add values 500 and 200 in one shot?
sales_amounts.append(500,200)

# Did it work?

TypeError: ignored

In [20]:
# No, because append takes only 1 argument. How to add more than one values in one shot?
# Pass the values as another list but using extend() method
sales_amounts.extend([500,200])

In [21]:
# Let's check what the list has now
sales_amounts

[2000, 900, 50, 500, 200]

**Phew!!** Quite a **long exercise**

**However**, we are sure it's **worth it** as we've explored most of the important **functions** to work with **lists**

**By the way**, We should **revisit** ways to **access/slice/dice** a list. It's **pretty interesting**, let's go :    

---------------------

**Scenario - 3 :**

Your list **sales_amounts** has all the required values now : i.e **2000,700,900,50,500,200**. How will you achieve below **tasks**?

* Access **all elements** of the list from **index 2 onwards**
* Access **all elements** of the list from **beginning till index 3 (excluded)**
* Access **all elements** of the list from **beginning till index 3 (included)**
* Access **all elements** of the list from **index 1 till index 3 (excluded)**
* Access **last value** of the list
* Access **last 2 values**
* Check whether the value **1000** is **there in the list or not**

In [ ]:
# Re-create the list 
sales_amounts = [2000,700,900,50,500,200]

In [ ]:
# Access all elements of the list from index 2 onwards
sales_amounts[2:]

In [ ]:
# Access all elements of the list from beginning till index 3 (excluded)
sales_amounts[:3]

# Again, little strange. But, if you wish to exclude item at index 3, the value after the : symbol should be 3 itself

In [ ]:
# Access all elements of the list from beginning till index 3 (included)
sales_amounts[:4]

# If you wish to include item at index 3, pass the value 4 (one more than 3) after : symbol

In [ ]:
# Access all elements of the list from index 1 till index 3 (excluded)
sales_amounts[1:3]

In [ ]:
# Access last value of the list
sales_amounts[-1]

In [ ]:
# Access last 2 values
sales_amounts[-2:]

In [ ]:
# Check if 1000 exists in the list or not
1000 in sales_amounts

**Great job guys!**

You've come a **long way** learning about working with **seqential data types** like **lists**

Wish to explore lists further? Here are some good references you should definitely go through :     

* **Accessing** list items / Slicing/Dicing : [here](https://www.w3schools.com/python/python_lists_access.asp)
* **Change** list items : [here](https://www.w3schools.com/python/python_lists_change.asp)
* **Add to** lists : [here](https://www.w3schools.com/python/python_lists_add.asp)
* **Remove from** lists : [here](https://www.w3schools.com/python/python_lists_remove.asp)

---------------------------
**Scenario - 4 :**

Now, let's go back to **Scenario - 1** where we were trying to **print** the **discount amounts**. 

We tried the below code :       

![](https://raw.githubusercontent.com/mentorskool/python-essentials/main/Module-6-PY-Learning-4/imgs/06-lists-01.png)

* Do you see a **problem** here?
  * We have to **declare** a **new variable** for **discount calculation** for **every item member** of the list **again and again**
  * The code is getting **repeated**
  * Imagine doing it for a list with **100 items!**

* How do we **solve** this problem?
* How do we **solve** a **general problem** of conveniently **repeating a set of tasks** without writing a **lot of repeated code**?

* **Enter** fundamental programming concept of **looping**!

In [22]:
# Let's check the below code :

for x in sales_amounts :
  print('The discount amount is',x*0.2)

The discount amount is 400.0
The discount amount is 180.0
The discount amount is 10.0
The discount amount is 100.0
The discount amount is 40.0

**Wait**, What just happened?

**2 lines of code** and we are **done!!**

That's the **power of looping** and **simplicity** of doing that in **Python**!

Let's **read the code** this way :    

**For** every **item** belonging to the list **sales_amounts**, **store** the item in **variable x**, then **multiply x by 0.2 (20%)** and keep **printing the results** until we reach the **end of the list**

-----------------------------------------------------------

**Scenario - 5 :**

Refer to the **Sales** and **Quantity** column of the **order details** once again :

![](https://raw.githubusercontent.com/mentorskool/python-essentials/main/Module-6-PY-Learning-4/imgs/03-order-details-03.png)

How do we **print** the **unit prices** using **loops**?

Well, to **calculate** unit prices, we need **access** to both **Sales** and **Quantity** values **at once**.

Let's **try** this below :

In [ ]:
# Let's store sales values in one list
sales = [2000,700,900,50,500,200]

# Let's store quantity values in another list
qty = [2,3,5,7,6,9]

# Now check out the below cod
for i in range(len(sales)):
  print('The unit price is :',sales[i] / qty[i])

Let's **dissect** the **code** above :      

* We already know the role of **for**
* **i** here is a **variable** as described before. The **difference** here is that instead of storing the **actual item** of the list, it stores the **index of that item**
* **len()** is a **function** which returns the **length** (**total count of members**) of the list
* **range(x)** is a function which **generates** values from **0** to **one less than number x**. This is **needed** because the **variable i** needs to **loop** through numbers from **0 to x-1** instead of **1 to x**

-----------------------------
**Scenario - 6 :**

Continuing with **Scenario - 5**, How can we **write** the **unit price** in a **better way** as shown below?

* The **unit price** of **Bush Somerset Collection Bookcase** is **1000.0**
* The **unit price** of **Hon Deluxe Fabric Upholstered Stacking Chairs** is **233.33333333333334**

Let's check out the code below :

In [23]:
# Let's store sales values in one list
sales = [2000,700,900,50,500,200]

# Let's store quantity values in another list
qty = [2,3,5,7,6,9]

# Let's store product names in another list
products = ['Bush Somerset Collection Bookcase',
'Hon Deluxe Fabric Upholstered Stacking Chairs',
'Bretford CR4500 Series Slim Rectangular Table',
'Eldon Expressions Wood and Plastic Desk Accessories',
'Mitel 5320 IP Phone VoIP phone',
'Chromcraft Rectangular Conference Tables']

# Now check out the below cod
for i in range(len(sales)):
  print('The unit price of ' + products[i] + ' is : ',round(sales[i] / qty[i],2)) # Recall operator overloading? 
  
# In the above line, three pieces of texts are being concatenated together with the help of + symbol
# Part 1 : 'The unit price of '
# Part 2 : product[i] which is the name of the product at ith index of the list
# Part 3 : ' is : '
# Also, check the usage of round() function to round off the excess digits

The unit price of Bush Somerset Collection Bookcase is :  1000.0
The unit price of Hon Deluxe Fabric Upholstered Stacking Chairs is :  233.33
The unit price of Bretford CR4500 Series Slim Rectangular Table is :  180.0
The unit price of Eldon Expressions Wood and Plastic Desk Accessories is :  7.14
The unit price of Mitel 5320 IP Phone VoIP phone is :  83.33
The unit price of Chromcraft Rectangular Conference Tables is :  22.22

-----------------------------------
**Task - 1 :**

* Check the **list** containing **quantity values** above : **2,3,5,7,6,9**
* **Loop through** the list and **print** only those **quantity values** which are an **even number**

In [ ]:
# Type your code below :

---------------------------------------------
**Task - 2 :**

* Refer back to **Scenario - 1**
* **Loop through** all the **sales values** belonging to the category **Furniture**
* Apply **20% discount** to each
* Calculate **sales amount after discount**
* **Store** the **after discount sales values** in a **new list**
* Print the **new list**

In [ ]:
# Let's store sales values in one list
sales = [2000,700,900,50,500,200]
discount = 0.2 # 20%

# Type your code below



# Expected Output
# sales_after_discount = [1600,560,720,40,400,160]

------------------------------------------------
**Important Follow up discussion :**

We observed how we can write more **nicely readable print statements** above. Let's look at **few more cases** and try printing well formatted output. 

* Given Sales amount as **1000** and discount value as **20.5%**, How will you print a statement like :  **The discount applied on amount of 1000.0 is 20.5%**

* Given Customer name as **Jack Ryan**, date of birth as **22-Feb-1992** and credit score as **9.8**, How will you print a statement like : **Customer Jack Ryan was born on 22-Feb-1992 and has a credit score of 9.8**

[Here](https://realpython.com/python-f-strings/) is a **good read** on the **journey** of **print** statement's **output formatting**. 
It started with **%formatting**, **str.format()** and evolved into an **easy** and **convenient** **f-string** method. Do spend some time!

In [ ]:
# Give examples of % literals




# Give examples of f-strings